### PR TITLE
Fix Jinja2 error

### PR DESCRIPTION
**Pull request by vladsaveliev**
To fix deploy_auth deployment: https://ci.hail.populationgenomics.org.au/batches/8052
For context: https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch.20Dev/topic/markupsafe.20error

### CODE REVIEW

**Review by lgruen — APPROVED** [review]
Thanks! Odd that only we are running into this though? Thanks for asking about in on Zulip.

**Comment by vladsaveliev** [comment]
@lgruen - the issue is very new. On the time of the PR, it was a few hours old.

**Comment by vladsaveliev** [comment]
UP: Success! https://ci.hail.populationgenomics.org.au/batches/8071

**Comment by lgruen** [comment]
> @lgruen - the issue is very new. On the time of the PR, it was a few hours old.

Got it, thanks!

**Pull request merged**
